### ISSUE TITLE
wp cv ext commands review and comments

### ISSUE THREAD

**Issue by kcristiano** [christianwach/cli-tools-for-civicrm#1]
tl;dr:   Really good implementation.  Commands work as documented.   Could use some improvements to ease adoption from those transitioning from `cv`

```
usage: 
wp cv ext disable <key-or-name> [--extpath=<extpath>] [--yes]
   or: wp cv ext download <key-or-name> [--install] [--yes]
   or: wp cv ext enable <key-or-name> [--extpath=<extpath>] [--yes]
   or: wp cv ext info <key-or-name> [--local] [--remote] [--format=<format>]
   or: wp cv ext install <key-or-name> [--extpath=<extpath>] [--yes]
   or: wp cv ext list [--local] [--remote] [--refresh] [--format=<format>]
   or: wp cv ext uninstall <key-or-name> [--extpath=<extpath>] [--yes]
   or: wp cv ext update-db
```

- `wp cv ext list`
  - Can we support `fields=`  such as `wp plugin list --fields=name,status,update,version` otherwise we receive a bit too much information (wraps on the screen)
  - typical usage in `cv` is `cv ext:list -L --columns=key,name,status,version` would be good to do `wp cv ext:list -L --fields=key,name,status,version`
  - `wp cv ext` is looking for `--local` can we add an alias for `--L`  as well as `--remote` as `--R`
- `wp cv ext download` `wp cv ext enable` `wp cv ext install` `wp cv ext uninstall` only supports a single extension at a time, `cv` allows multiple.
- `wp cv ext install` `wp cv ext enable`  These look to be aliases of one another.   Is that correct?
- `wp cv ext update-db --vvv`  is not verbose like `cv ext:upgrade-db -vvv`
